version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always

  api:
    build: .
    container_name: precogas-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
